name: Laravel CI
on: [push]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Clone PHP_CodeSniffer
        run: |
          git clone https://github.com/squizlabs/PHP_CodeSniffer.git

      - name: Run phpcs
        run: |
          PHP_CodeSniffer/bin/phpcs --standard=PSR2 app/
